// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github_installations.sql

package entities

import (
	"context"

	"github.com/google/uuid"
)

const createGithubInstallation = `-- name: CreateGithubInstallation :one
INSERT INTO github_installations (
  org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login, is_active
`

type CreateGithubInstallationParams struct {
	OrgID               uuid.UUID `json:"org_id"`
	InstallationID      int64     `json:"installation_id"`
	InstallationLogin   string    `json:"installation_login"`
	InstallationLoginID int64     `json:"installation_login_id"`
	InstallationType    string    `json:"installation_type"`
	SenderID            int64     `json:"sender_id"`
	SenderLogin         string    `json:"sender_login"`
}

func (q *Queries) CreateGithubInstallation(ctx context.Context, arg CreateGithubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, createGithubInstallation,
		arg.OrgID,
		arg.InstallationID,
		arg.InstallationLogin,
		arg.InstallationLoginID,
		arg.InstallationType,
		arg.SenderID,
		arg.SenderLogin,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.InstallationID,
		&i.InstallationLogin,
		&i.InstallationLoginID,
		&i.InstallationType,
		&i.SenderID,
		&i.SenderLogin,
		&i.IsActive,
	)
	return i, err
}

const getGithubInstallation = `-- name: GetGithubInstallation :one
SELECT id, created_at, updated_at, org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login, is_active
FROM github_installations
WHERE id = $1
`

func (q *Queries) GetGithubInstallation(ctx context.Context, id uuid.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallation, id)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.InstallationID,
		&i.InstallationLogin,
		&i.InstallationLoginID,
		&i.InstallationType,
		&i.SenderID,
		&i.SenderLogin,
		&i.IsActive,
	)
	return i, err
}

const getGithubInstallationByInstallationID = `-- name: GetGithubInstallationByInstallationID :one
SELECT id, created_at, updated_at, org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login, is_active
FROM github_installations
WHERE installation_id = $1
`

func (q *Queries) GetGithubInstallationByInstallationID(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallationByInstallationID, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.InstallationID,
		&i.InstallationLogin,
		&i.InstallationLoginID,
		&i.InstallationType,
		&i.SenderID,
		&i.SenderLogin,
		&i.IsActive,
	)
	return i, err
}

const getGithubInstallationByInstallationIDAndInstallationLogin = `-- name: GetGithubInstallationByInstallationIDAndInstallationLogin :one
SELECT id, created_at, updated_at, org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login, is_active
FROM github_installations
WHERE installation_id = $1 AND installation_login = $2
`

type GetGithubInstallationByInstallationIDAndInstallationLoginParams struct {
	InstallationID    int64  `json:"installation_id"`
	InstallationLogin string `json:"installation_login"`
}

func (q *Queries) GetGithubInstallationByInstallationIDAndInstallationLogin(ctx context.Context, arg GetGithubInstallationByInstallationIDAndInstallationLoginParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallationByInstallationIDAndInstallationLogin, arg.InstallationID, arg.InstallationLogin)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.InstallationID,
		&i.InstallationLogin,
		&i.InstallationLoginID,
		&i.InstallationType,
		&i.SenderID,
		&i.SenderLogin,
		&i.IsActive,
	)
	return i, err
}

const updateGithubInstallation = `-- name: UpdateGithubInstallation :one
UPDATE github_installations
SET
    org_id = $2,
    installation_id = $3,
    installation_login = $4,
    installation_login_id = $5,
    installation_type = $6,
    sender_id = $7,
    sender_login = $8,
    is_active = $9
WHERE id = $1
RETURNING id, created_at, updated_at, org_id, installation_id, installation_login, installation_login_id, installation_type, sender_id, sender_login, is_active
`

type UpdateGithubInstallationParams struct {
	ID                  uuid.UUID `json:"id"`
	OrgID               uuid.UUID `json:"org_id"`
	InstallationID      int64     `json:"installation_id"`
	InstallationLogin   string    `json:"installation_login"`
	InstallationLoginID int64     `json:"installation_login_id"`
	InstallationType    string    `json:"installation_type"`
	SenderID            int64     `json:"sender_id"`
	SenderLogin         string    `json:"sender_login"`
	IsActive            bool      `json:"is_active"`
}

func (q *Queries) UpdateGithubInstallation(ctx context.Context, arg UpdateGithubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, updateGithubInstallation,
		arg.ID,
		arg.OrgID,
		arg.InstallationID,
		arg.InstallationLogin,
		arg.InstallationLoginID,
		arg.InstallationType,
		arg.SenderID,
		arg.SenderLogin,
		arg.IsActive,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.InstallationID,
		&i.InstallationLogin,
		&i.InstallationLoginID,
		&i.InstallationType,
		&i.SenderID,
		&i.SenderLogin,
		&i.IsActive,
	)
	return i, err
}
