// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubInstallation struct {
	ID                  pgtype.UUID
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	OrgID               pgtype.UUID
	InstallationID      int64
	InstallationLogin   string
	InstallationLoginID int64
	InstallationType    pgtype.Text
	SenderID            int64
	SenderLogin         string
	Status              pgtype.Text
}

type GithubOrg struct {
	ID             pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	InstallationID pgtype.UUID
	GithubOrgID    int64
	Name           string
}

type GithubRepo struct {
	ID             pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	RepoID         pgtype.UUID
	InstallationID pgtype.UUID
	GithubID       int64
	Name           string
	FullName       string
	Url            string
	IsActive       pgtype.Bool
}

type GithubUser struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.UUID
	GithubID    int64
	GithubOrgID pgtype.UUID
	Login       string
}

type Messaging struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Provider  string
	Kind      string
	LinkTo    pgtype.UUID
	Data      []byte
}

type OauthAccount struct {
	ID                pgtype.UUID
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	UserID            pgtype.UUID
	Provider          string
	ProviderAccountID string
	ExpiresAt         pgtype.Timestamp
	Type              pgtype.Text
}

type Org struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	OrgID     pgtype.UUID
	Name      string
	Slug      string
}

type Repo struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	OrgID         pgtype.UUID
	Name          string
	Provider      string
	ProviderID    string
	DefaultBranch pgtype.Text
	IsMonorepo    pgtype.Bool
	Threshold     pgtype.Int4
	StaleDuration pgtype.Interval
}

type Team struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	OrgID     pgtype.UUID
	Name      string
	Slug      string
}

type TeamUser struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      pgtype.Text
	IsActive  bool
	IsAdmin   bool
}

type User struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	OrgID      pgtype.UUID
	Email      string
	FirstName  pgtype.Text
	LastName   pgtype.Text
	Password   pgtype.Text
	IsActive   bool
	IsVerified bool
}
