// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: ctrlplane/common/v1/uuid.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a universally unique identifier (UUID) as a string.
//
// A native 18-byte representation, conforming to RFC 4122 section 4.1.2, would
// offer optimal performance in terms of size. However, it requires custom
// serialization logic across platforms, making it impractical for current
// needs.
//
// Native UUID representation (for future reference):
//
//	message UUID {
//	  fixed16 time_low = 1;                  // 32 bits: The low field of the timestamp.
//	  fixed16 time_mid = 2;                  // 16 bits: The middle field of the timestamp.
//	  fixed16 time_hi_and_version = 3;       // 16 bits: The high field of the timestamp multiplexed with the version number.
//	  fixed16 clock_seq_hi_and_reserved = 4; // 8 bits: The high field of the clock sequence multiplexed with the variant.
//	  fixed16 clock_seq_low= 5;             // 8 bits: The low field of the clock sequence.
//	  fixed64 node = 6;                      // 48 bits: The spatially unique node identifier.
//	 }
//
// This string representation provides universal compatibility and simpler
// implementation at the cost of increased size. Future optimization may
// consider a native format for improved efficiency.
//
// See https://github.com/protocolbuffers/protobuf/issues/2224 for relevant
// discussion.
type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_ctrlplane_common_v1_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_ctrlplane_common_v1_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_ctrlplane_common_v1_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_ctrlplane_common_v1_uuid_proto protoreflect.FileDescriptor

var file_ctrlplane_common_v1_uuid_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x63, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0xd7, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x74, 0x72, 0x6c,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42,
	0x09, 0x55, 0x75, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x6f,
	0x2e, 0x62, 0x72, 0x65, 0x75, 0x2e, 0x69, 0x6f, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x6d, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x43, 0x43, 0x58, 0xaa, 0x02, 0x13, 0x43, 0x74, 0x72, 0x6c, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x13,
	0x43, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1f, 0x43, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5c,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x43, 0x74, 0x72, 0x6c, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x3a, 0x3a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ctrlplane_common_v1_uuid_proto_rawDescOnce sync.Once
	file_ctrlplane_common_v1_uuid_proto_rawDescData = file_ctrlplane_common_v1_uuid_proto_rawDesc
)

func file_ctrlplane_common_v1_uuid_proto_rawDescGZIP() []byte {
	file_ctrlplane_common_v1_uuid_proto_rawDescOnce.Do(func() {
		file_ctrlplane_common_v1_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_ctrlplane_common_v1_uuid_proto_rawDescData)
	})
	return file_ctrlplane_common_v1_uuid_proto_rawDescData
}

var file_ctrlplane_common_v1_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ctrlplane_common_v1_uuid_proto_goTypes = []any{
	(*UUID)(nil), // 0: ctrlplane.common.v1.UUID
}
var file_ctrlplane_common_v1_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ctrlplane_common_v1_uuid_proto_init() }
func file_ctrlplane_common_v1_uuid_proto_init() {
	if File_ctrlplane_common_v1_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ctrlplane_common_v1_uuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ctrlplane_common_v1_uuid_proto_goTypes,
		DependencyIndexes: file_ctrlplane_common_v1_uuid_proto_depIdxs,
		MessageInfos:      file_ctrlplane_common_v1_uuid_proto_msgTypes,
	}.Build()
	File_ctrlplane_common_v1_uuid_proto = out.File
	file_ctrlplane_common_v1_uuid_proto_rawDesc = nil
	file_ctrlplane_common_v1_uuid_proto_goTypes = nil
	file_ctrlplane_common_v1_uuid_proto_depIdxs = nil
}
